Fix babel-jest test runner setup
vuejs/vue-test-utils-jest-example pull request #16
Opened 2018-03-12 17:26 UTC by macedigital

When checking out the example project all tests fail due to test-runner compilation issues which resolve around babel/jest not transpiling the code correctly.

When changing `.babelrc` to default to a browser environment everything starting working again.

Maybe there are other solutions. Also, I'd be interested why the current setup seems to be working on some people's computers.

### Environment

```sh
nvm use lts/carbon
# Now using node v8.10.0 (npm v5.6.0)
```

### Steps to reproduce

```sh
git clone https://github.com/vuejs/vue-test-utils-jest-example.git
cd vue-test-utils-jest-example
npm install
npm test
```

### Expected Behavior:
Tests run (but do not necessarily pass)

### Actual Behavior
```txt
 FAIL  test/Message.spec.js
  ● Test suite failed to run

    /home/REDACTED/vue-test-utils-jest-example/test/Message.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallow } from '@vue/test-utils';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
```

2018-03-12 17:39 UTC, eddyerburgh requested changes
Thanks for the PR 😀

We generally use circle, not travis. Could you please remove the travis.yml. If you want, you could add config for a circle build

2018-03-12 21:30 UTC, macedigital commented
@eddyerburgh Thanks for the fast feedback :smiley: I reverted the `.travis.yml` related commit.

It is a bit strange, though, that on a co-workers' machine tests worked before making the change, but now fail with `Unexpected token import` after. So, maybe I should run some more field tests?

2018-03-13 06:35 UTC, eddyerburgh approved these changes
Thanks 😀

2018-03-13 06:37 UTC, eddyerburgh commented
Ah, I just saw your comment. There's a yarn.lock and a package-lock file in the repo, so that could be the problem. Did one of you use npm and one use yarn to install dependencies?

If you could delete the package-lock, and install with yarn, and check if that compiles correctly

2018-03-17 20:32 UTC, macedigital commented
@eddyerburgh Hi, sorry again for the late reply.

See my comment on #17, the issue isn't related to either `yarn.lock` or `package-lock.json` (I really tried to reproduce it this way :smile: )

Let me know if you think it still makes sense to merge this PR (as it is more of a workaround than a solution).

2018-03-17 21:06 UTC, eddyerburgh commented
thanks for the update  😄 . 
 
I think we should close the PR since it works correctly for most people, and as you said it's more of a workaround than a solution.

2018-03-17 21:06 UTC, closed without merging